version: '3.7'

services:
  web:
    build:
      context: ./services/heater_control_app
      dockerfile: Dockerfile.prod
    command: gunicorn heater_control.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/services/heater_control_app/staticfiles
      - media_volume:/usr/src/services/heater_control_app/mediafiles
    env_file: ./environments/prod
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    ports:
      - 5430:5432
    env_file: ./environments/prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/usr/src/services/heater_control_app/staticfiles
      - media_volume:/usr/src/services/heater_control_app/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
  mqttbroker:
    build: ./services/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto_data:/mosquitto/data/
      - mosquitto_log:/mosquitto/log/
volumes:
  postgres_data:
  static_volume:
  media_volume:
  mosquitto_data:
  mosquitto_log:
