version: '3.7'

services:
  web:
    build: ./services/heater_control_app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    ports:
      - 5430:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: