version: '3.7'

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ./services/heater_control_app
      dockerfile: Dockerfile
    volumes:
      - ./services/heater_control_app/:/usr/src/services/heater_control_app/
    env_file: ./environments/dev
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    ports:
      - 5430:5432
    env_file: ./environments/dev.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
