version: '3.7'

services:
  apps_open_api:
    build:
      context: ../services_repos/apps_open_api
      dockerfile: Dockerfile.prod
    volumes:
      - apps_open_api_static_volume:/usr/src/apps_open_api/staticfiles
      - media_volume:/mediafiles
    env_file:
      - ./environments/prod/appsapi
      - ./environments/prod/dbinfo
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    ports:
      - 5430:5432
    env_file:
      - ./environments/prod/postgres
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
  nginx:
    build: ../services_repos/nginx
    volumes:
      - apps_open_api_static_volume:/usr/services/apps_open_api/staticfiles
      - mqttauth_static_volume:/usr/services/mqttauthorization/staticfiles
      - media_volume:/usr/services/apps_open_api/mediafiles
    ports:
      - 1337:80
    depends_on:
      - apps_open_api
      - mqttauthorization
      - mqtthttpapi
  mqttbroker:
    build: ../services_repos/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    env_file:
      - ./environments/prod/dbinfo
    volumes:
      - type: volume
        source: mqttbroker_data
        target: /data/
    depends_on:
      - db
      - apps_open_api
  mqttclientobserver:
    build: ../services_repos/mqtt_client_observer
    depends_on:
      - mqttbroker
    env_file:
      - ./environments/prod/mqttbrokerinfo
  mqtthttpapi:
    build: ../services_repos/mqtt_http_api
    expose:
      - 8888
    env_file:
      - ./environments/prod/mqttbrokerinfo
    depends_on:
      - mqttbroker
  mqttauthorization:
    build:
      context: ../services_repos/mqttauthorization
      dockerfile: Dockerfile.prod
    env_file:
      - ./environments/prod/mqttauthorizationapi
      - ./environments/prod/dbinfo
    ports:
      - 8001:8001
    depends_on:
      - db
    volumes:
      - mqttauth_static_volume:/usr/src/mqttauthorization/staticfiles
volumes:
  mqttauth_static_volume:
  mqttbroker_data:
  mqttbroker_log:
  postgres_data_prod:
  apps_open_api_static_volume:
  media_volume:
