version: '3.7'

services:
  apps_open_api:
    build:
      context: ../services_repos/apps_open_api
      dockerfile: Dockerfile
    volumes:
      - ../services_repos/apps_open_api/:/usr/src/apps_open_api/
      - ../mediafiles:/mediafiles
    env_file:
      - ./environments/dev/apps_open_api
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    ports:
      - 5430:5432
    env_file:
      - ./environments/dev/postgres_info
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
      - ./sql_init/:/docker-entrypoint-initdb.d/
  mqtt_broker:
    build: ../services_repos/mqtt_broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ../services_repos/mqtt_broker/config/:/etc/mosquitto/config
      - ../services_repos/mqtt_broker/data/:/etc/mosquitto/data
      - ../services_repos/mqtt_broker/log/:/etc/mosquitto/log
  mqtt_client_observer:
    build: ../services_repos/mqtt_client_observer
    volumes:
      - ../services_repos/mqtt_client_observer:/usr/src/mqtt_client_observer
    env_file:
      - ./environments/dev/mqtt_broker_info
    depends_on:
      - mqtt_broker
  mqtt_http_api:
    build: ../services_repos/mqtt_http_api
    ports:
      - 8888:8888
    env_file:
      - ./environments/dev/mqtt_broker_info
    depends_on:
      - mqtt_broker
  mqtt_access_control_api:
    build:
      context: ../services_repos/mqtt_access_control_api
      dockerfile: Dockerfile
    env_file:
      - ./environments/dev/mqtt_access_control_api_info
    volumes:
      - ../services_repos/mqtt_access_control_api/:/usr/src/mqtt_access_control_api/
    ports:
      - 8001:8001
    depends_on:
      - db
volumes:
  postgres_data_dev:
