version: '3.7'
# Call CODEPATH=../dev/services_repos; docker-compose -f docker-compose.build.prod.yml build
services:
  apps_open_api:
    build:
      context: $CODEPATH/apps_open_api
      dockerfile: Dockerfile.prod
  nginx:
    build: $CODEPATH/nginx
  mqtt_broker:
    build: $CODEPATH/mqtt_broker
  mqtt_client_observer:
    build: $CODEPATH/mqtt_client_observer
  mqtt_http_api:
    build: $CODEPATH/mqtt_http_api
  mqtt_access_control_api:
    build:
      context: $CODEPATH/mqtt_access_control_api
      dockerfile: Dockerfile.prod
