version: '3.7'

services:
  apps_open_api:
    image: apps_open_api_service:$TAG
    volumes:
      - apps_open_api_static_volume:/usr/src/apps_open_api/staticfiles
      - media_volume:/mediafiles
    env_file:
      - ./apps_open_api
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    ports:
      - 5430:5432
    env_file:
      - ./postgres_info
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
      - ../../sql_init/:/docker-entrypoint-initdb.d/
  nginx:
    image: nginx_service:$TAG
    volumes:
      - apps_open_api_static_volume:/usr/services/apps_open_api/staticfiles
      - mqttauth_static_volume:/usr/services/mqtt_access_control_api/staticfiles
      - media_volume:/usr/services/apps_open_api/mediafiles
    ports:
      - 80:80
    depends_on:
      - apps_open_api
      - mqtt_access_control_api
      - mqtt_http_api
  mqtt_broker:
    image: mqtt_broker_service:$TAG
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - type: volume
        source: mqtt_broker_data
        target: /data/
    depends_on:
      - mqtt_access_control_api
    env_file:
      - ./mqtt_broker_environment
  mqtt_client_observer:
    image: mqtt_client_observer_service:$TAG
    depends_on:
      - mqtt_broker
    env_file:
      - ./mqtt_broker_info
      - ./mqtt_observer_info
  mqtt_http_api:
    image: mqtt_http_api_service:$TAG
    expose:
      - 8002
    env_file:
      - ./mqtt_broker_info
      - ./mqtt_http_api_info
    depends_on:
      - mqtt_broker
  mqtt_access_control_api:
    image: mqtt_access_control_api_service:$TAG
    env_file:
      - ./mqtt_access_control_api_info
    ports:
      - 8001:8001
    depends_on:
      - db
    volumes:
      - mqttauth_static_volume:/usr/src/mqtt_access_control_api/staticfiles
volumes:
  mqttauth_static_volume:
  mqtt_broker_data:
  postgres_data_prod:
  apps_open_api_static_volume:
  media_volume:
