version: '3.7'

services:
  apps_open_api:
    image: apps_open_api_service:$TAG
    build:
      context: ./services_repos/apps_open_api
      dockerfile: Dockerfile
    volumes:
      - ./services_repos/apps_open_api/:/usr/src/apps_open_api/
      - ./mediafiles:/mediafiles
    env_file:
      - ./apps_open_api
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    ports:
      - 5430:5432
    env_file:
      - ./postgres_info
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
      - ../../sql_init/:/docker-entrypoint-initdb.d/
  mqtt_broker:
    image: mqtt_broker_service:$TAG
    build: ./services_repos/mqtt_broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./services_repos/mqtt_broker/config/:/etc/mosquitto/config
      - ./services_repos/mqtt_broker/data/:/etc/mosquitto/data
      - ./services_repos/mqtt_broker/log/:/etc/mosquitto/log
    depends_on:
      - mqtt_access_control_api
    env_file:
      - ./mqtt_broker_environment
  mqtt_client_observer:
    image: mqtt_client_observer_service:$TAG
    build: ./services_repos/mqtt_client_observer
    volumes:
      - ./services_repos/mqtt_client_observer:/usr/src/mqtt_client_observer
    env_file:
      - ./mqtt_broker_info
      - ./mqtt_observer_info
    depends_on:
      - mqtt_broker
  mqtt_http_api:
    image: mqtt_http_api_service:$TAG
    build: ./services_repos/mqtt_http_api
    ports:
      - 8002:8002
    env_file:
      - ./mqtt_broker_info
      - ./mqtt_http_api_info
    depends_on:
      - mqtt_broker
  mqtt_access_control_api:
    image: mqtt_access_control_api_service:$TAG
    build:
      context: ./services_repos/mqtt_access_control_api
      dockerfile: Dockerfile
    env_file:
      - ./mqtt_access_control_api_info
    volumes:
      - ./services_repos/mqtt_access_control_api/:/usr/src/mqtt_access_control_api/
    ports:
      - 8001:8001
    depends_on:
      - db
volumes:
  postgres_data_dev:
